name: merlo

concurrency:
  group: $-$
  cancel-in-progress: true

on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master

jobs:
  build:
    uses: VeryGoodOpenSource/very_good_workflows/.github/workflows/flutter_package.yml@v1
    with:
      flutter_channel: stable
      min_coverage: 0
      setup: "flutter pub global activate very_good_cli && export PATH=$PATH:$HOME/.pub-cache/bin && flutter gen-l10n && dart run build_runner build --delete-conflicting-outputs && dart format --line-length 80 lib"
